### ISSUE TITLE
Components.getComponent can fetch an uninitialized component

### ISSUE THREAD

**Issue by xethlyx** [rbxts-flamework/core#116]
Minimal repro:

```ts
import type { Components } from '@flamework/components';
import { BaseComponent, Component } from '@flamework/components';
import type { OnStart } from '@flamework/core';
import { Service } from '@flamework/core';
import { Workspace } from '@rbxts/services';

@Component({
	tag: 'Test',
})
export class TestA extends BaseComponent implements OnStart {
	constructor(private readonly components: Components) {
		super();
	}

	onStart() {
		print(this.components.getComponent<TestB>(this.instance)!.myValue);
	}
}

@Component({
	tag: 'Test',
})
export class TestB extends BaseComponent implements OnStart {
	myValue = 'i exist';

	constructor(private readonly testA: TestA) {
		super();
	}

	onStart() {}
}

@Service({})
export class TestService implements OnStart {
	constructor(private readonly components: Components) {}
	onStart() {
		const part = new Instance('Part');
		part.AddTag('Test');
		part.Parent = Workspace;
		this.components.getComponent<TestB>(part);
	}
}
```

Output: `nil`

Here is an overview of the issue:

* TestB is added to ID mapping
* setupComponent is called on TestB
* Eagerly load TestA as it is a dependency of TestB and has the corresponding tag
* TestA runs its constructor
* TestA runs OnStart
* TestB is in ID mapping despite being half constructed
* TestB runs its constructor

I suspect this can be fixed if these lines are moved under setupComponent: https://github.com/rbxts-flamework/components/blob/283b54adaad51978de8f773c95c7bf486d8391b6/src/components.ts#L594-L596

**Comment by Fireboltofdeath** [comment]
This is because `TestA` and `TestB` cyclically depend on eachother's construction.  The component has to be eagerly put into the registry to avoid infinite recursion in cases like this, so I've added a separate check for whether a component is still in construction, in which case it will return `undefined`, or error in the case of `addComponent`.

The polymorphic IDs are specifically for the polymorphic APIs (which doesn't include `getComponent`) such as `getAllComponents` and `getComponents` so moving that below `setupComponent` wouldn't fix this specific case, but it does fix similar cases with those APIs.

Fixed in https://github.com/rbxts-flamework/components/commit/f61187fd6a6f8596ffd68a237d692ace46182d63
