### ISSUE TITLE
Hash improvements

### ISSUE THREAD

**Issue by safazi** [rbxts-flamework/core#49]
- Option to only hash in production builds (for debugging)
- Shorthand (instead of Flamework.hash, maybe just $hash()?)
- Hash an entire enum

Love the idea of hash, let's make it better!

**Comment by Fireboltofdeath** [comment]
> Hash an entire enum

Could you elaborate this? What do you mean by hashing an enum?

**Comment by safazi** [comment]
A way to hash many strings at once.

```ts
@Hash()
enum Keys {
    Test
}

const map = {
    [Keys.Test]: 1
}
```
could compile to
```ts
const map = {
    'asdasdasd-asdasdasdasd-asdasdasd-asdasd': 1
}
```
or something along those lines

Just any way to hash many things instead of calling `hash` a lot.

**Comment by Fireboltofdeath** [comment]
I'm perhaps a bit late on this but I feel like all of the bulletins included in the original post have mostly been solved by Flamework's modding API.

1. `Flamework.hash` doesn't directly support this, but the `Modding.Obfuscate` metadata does if you write your own user macro.
2. You can write your own user macro instead of `Flamework.hash` with however short of a name you want (minus the $ prefix)

The third one is a bit more nuanced but I don't think this is necessary with Flamework user macros and would probably be best implemented in a separate transformer like [rbxts-transform-guid](https://github.com/roblox-aurora/rbxts-transform-guid/tree/master) (although this one doesn't appear to preserve types which could cause issues with incremental compilation and typechecking errors)

With Flamework user macros, I think it'd be more idiomatic to automatically convert names into their hashed versions rather than having the user do so manually. Although, it's not currently possible to obfuscate property accesses (without intrinsics) but I intend to support that eventually.

I'm going to close this issue for the above reasons, but feel free to reopen it if you disagree.
